"""agregar codigo de verificacion a usuario

Revision ID: 94f7ac6aced4
Revises: c99d7e92504e
Create Date: 2026-09-23 10:13:57.741464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94f7ac6aced4'
down_revision: Union[str, Sequence[str], None] = 'c99d7e92504e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('codigo_verificacion', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True))
    op.add_column('usuario', sa.Column('codigo_verificacion_expira', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'codigo_verificacion_expira')
    op.drop_column('usuario', 'codigo_verificacion')
    # ### end Alembic commands ###
