"""esquema inicial grupo 1 - organizacion (v2)

Revision ID: c99d7e92504e
Revises: 
Create Date: 2026-09-22 01:42:37.685864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c99d7e92504e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciclo_ebr',
    sa.Column('id_ciclo', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_ciclo')
    )
    op.create_table('docente',
    sa.Column('id_docente', sa.Integer(), nullable=False),
    sa.Column('nombres', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellidos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.Date(), nullable=False),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_en', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_docente')
    )
    # docente.creado_por/modificado_por -> usuario.id_usuario se agregan mas abajo
    # via create_foreign_key: docente <-> usuario es una dependencia circular
    # (usuario.id_docente -> docente, docente.creado_por -> usuario), asi que
    # ninguna de las dos tablas puede llevar esa FK en su propio create_table.
    op.create_table('programa',
    sa.Column('id_programa', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_programa')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_docente', sa.Integer(), nullable=True),
    sa.Column('nombres', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellidos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.Date(), nullable=False),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_en', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_docente'], ['docente.id_docente'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_foreign_key('docente_creado_por_fkey', 'docente', 'usuario', ['creado_por'], ['id_usuario'])
    op.create_foreign_key('docente_modificado_por_fkey', 'docente', 'usuario', ['modificado_por'], ['id_usuario'])
    op.create_table('año_escolar',
    sa.Column('id_anio_escolar', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.Date(), nullable=False),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_en', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_anio_escolar')
    )
    op.create_table('colegio',
    sa.Column('id_colegio', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zona', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.Date(), nullable=False),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_en', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_colegio')
    )
    op.create_table('grado',
    sa.Column('id_grado', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_ciclo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ciclo'], ['ciclo_ebr.id_ciclo'], ),
    sa.PrimaryKeyConstraint('id_grado')
    )
    op.create_table('alumno',
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('nombres', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellidos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_colegio', sa.Integer(), nullable=False),
    sa.Column('id_grado', sa.Integer(), nullable=False),
    sa.Column('id_programa_actual', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.Date(), nullable=False),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_en', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_colegio'], ['colegio.id_colegio'], ),
    sa.ForeignKeyConstraint(['id_grado'], ['grado.id_grado'], ),
    sa.ForeignKeyConstraint(['id_programa_actual'], ['programa.id_programa'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_alumno')
    )
    op.create_table('periodo_academico',
    sa.Column('id_periodo_academico', sa.Integer(), nullable=False),
    sa.Column('id_anio_escolar', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.Date(), nullable=False),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_en', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_anio_escolar'], ['año_escolar.id_anio_escolar'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_periodo_academico')
    )
    op.create_table('alumno_programa_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('id_programa', sa.Integer(), nullable=False),
    sa.Column('id_periodo_academico', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.Date(), nullable=False),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_en', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumno.id_alumno'], ),
    sa.ForeignKeyConstraint(['id_periodo_academico'], ['periodo_academico.id_periodo_academico'], ),
    sa.ForeignKeyConstraint(['id_programa'], ['programa.id_programa'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('docente_colegio_grado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_docente', sa.Integer(), nullable=False),
    sa.Column('id_colegio', sa.Integer(), nullable=False),
    sa.Column('id_grado', sa.Integer(), nullable=False),
    sa.Column('id_periodo_academico', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.Date(), nullable=False),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('modificado_en', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_colegio'], ['colegio.id_colegio'], ),
    sa.ForeignKeyConstraint(['id_docente'], ['docente.id_docente'], ),
    sa.ForeignKeyConstraint(['id_grado'], ['grado.id_grado'], ),
    sa.ForeignKeyConstraint(['id_periodo_academico'], ['periodo_academico.id_periodo_academico'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('docente_colegio_grado')
    op.drop_table('alumno_programa_historial')
    op.drop_table('periodo_academico')
    op.drop_table('alumno')
    op.drop_table('grado')
    op.drop_table('colegio')
    op.drop_table('año_escolar')
    op.drop_constraint('docente_creado_por_fkey', 'docente', type_='foreignkey')
    op.drop_constraint('docente_modificado_por_fkey', 'docente', type_='foreignkey')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('rol')
    op.drop_table('programa')
    op.drop_table('docente')
    op.drop_table('ciclo_ebr')
    # ### end Alembic commands ###
